version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - /opt/data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    deploy:
     placement:
        constraints: [node.hostname == Docker01]
networks:                                
  jenkins:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: 1400
